name: aola
 
on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:   
    - cron: '0 5 * * *'   #国际标准时间，北京时间+8，即下午1点钟
 
jobs:
     - name: Setup Node.js
       uses: actions/setup-node@v2  #安装node.js
       with:
         node-version: '14'
          
     - name: Install Dependency       
       run: 
       node ./scripts/aoqi.js   #脚本存在根目录scripts文件夹下
 
